# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: tf
  - /task: multilabel_classification
  - /optimizer: adamw
  - /scheduler: plateau
  - /callbacks: [base, checkpoint]

train:
  monitor: val/accuracy # Needed for plateau scheduler
  mode: max

encoder: id

# we need this for classification!
decoder: id