_name_: chromatin_profile
dataset_name: chromatin_profile
ref_genome_path: '/liuzicheng/ljh/hyena-dna/data/hg38/hg38.ml.fa'
ref_genome_version: 'hg38'
data_path: '/liuzicheng/ljh/hyena-dna/data/chromatin_profile'
max_length: 1024
d_output: 919 
use_padding: True
padding_side: 'left'
add_eos: False
__l_max: ${.max_length}
shuffle: true  # set this as default!
