_name_: genomic_long_range_benchmark
dataset_name: bulk_rna_expression
dest_path: /liuzicheng/ljh/hyena-dna/data/genomics-long-range-benchmark
max_length: 2048
d_output: ${.${.dataset_name}.classes}
#l_output:max_length/128
l_output: 16
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
# these are used to find the right attributes automatically for each dataset
cage_prediction:
  train_len: 36086
  classes: 50
bulk_rna_expression:
  train_len: 22827
  classes: 2
variant_effect_gene_expression:
  train_len: 89060
  classes: 2


# there are 8 datasets in this suite, choose 1 at a time, with their corresponding settings
# name                                num_seqs        num_classes     median len    std
# dummy_mouse_enhancers_ensembl       1210            2               2381          984.4  
# demo_coding_vs_intergenomic_seqs    100_000         2               200           0
# demo_human_or_worm                  100_000         2               200           0
# human_enhancers_cohn                27791           2               500           0
# human_enhancers_ensembl             154842          2               269           122.6
# human_ensembl_regulatory            289061          3               401           184.3
# human_nontata_promoters             36131           2               251           0
# human_ocr_ensembl                   174756          2               315           108.1
